"""
The IR pipeline: conversation -> IR (one LLM call) -> deterministic validation
-> confirmation -> fixed FreeCAD builder.  Replaces unified/DFM/confirm/codegen/
code-edit chains for every non-perforated part.

Wired into TextToCADAgent.process_request_with_progress behind
`CAD_PIPELINE=ir` (default).  Set CAD_PIPELINE=legacy to fall back.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import time
from typing import AsyncIterator, Optional

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

from src.core import ir_render
from src.core.agent_chains import LOGS_DIR, log_template_io
from src.core.error_codes import as_user_error, error_code_of
from src.core.ir import format_questions, part_to_dict
from src.core.ir_geom import F
from src.core.ir_validate import validate
from src.core.models import AnalysisAndParameterCheckOutput
from src.core.templates_ir import extract_ir_template, patch_ir_template
from src.utils.cost_tracking_wrapper import ainvoke_with_cost_tracking

logger = logging.getLogger(__name__)

IR_PIPELINE = os.getenv("CAD_PIPELINE", "ir").strip().lower()
ASSEMBLY_MESSAGE = "We cannot currently create an assembly file. You can create file by file."
CAPABILITIES = ("I can model single sheet-metal parts (flat, round or triangular plates, bent brackets, covers, frames with holes, "
                "slots, tapped or countersunk holes, perforated sheets), square or round tubes with end cuts and holes, "
                "and T or I profiles. ")
IR_EXTRACT_LOG = os.path.join(LOGS_DIR, "ir_extract_template.log")

STUB_SCRIPT = '''# Generated by the IR pipeline: a fixed builder plus the part description below.
# Nothing in this file is model-specific code; edit the IR, not the script.
import os
import sys
import json

script_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
project_root = os.path.abspath(os.path.join(script_dir, "..", "..", ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

sanitized_title = %(title)r   # DO NOT CHANGE THIS VALUE
output_dir_abs = %(output_dir)r

IR = json.loads(%(ir_json)r)

from FreeCadUtil.build_from_ir import build_and_export
build_and_export(IR, sanitized_title, output_dir_abs, material=%(material)r)
'''


def use_ir_pipeline(state: dict, user_text: str) -> bool:
    """Route this session through the IR pipeline?  Perforated sheets and sessions
    that already hold legacy generated code stay on the legacy path."""
    if IR_PIPELINE != "ir":
        return False
    if state.get("perf_calc_result") is not None or state.get("perf_extracted_params") is not None:
        return False                      # a session already on the legacy perforated chain stays there
    if state.get("latest_code") and not state.get("latest_ir"):
        return False
    return True


def make_stub_script(ir: dict, title: str, material: Optional[str]) -> str:
    return STUB_SCRIPT % {
        "title": title,
        "output_dir": "/app/storage/%s/output" % title,
        "ir_json": json.dumps(ir, ensure_ascii=True, separators=(",", ":")),
        "material": material or ir.get("material") or "steel",
    }


def sanitize_title(name: Optional[str], fallback: str = "part") -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", (name or fallback)).strip("_")
    return (s or fallback)[:48]


def _parse_json(raw: str) -> dict:
    txt = (raw or "").strip()
    txt = re.sub(r"^```(?:json)?\s*|\s*```$", "", txt, flags=re.S)
    start, end = txt.find("{"), txt.rfind("}")
    if start < 0 or end < 0:
        raise ValueError("no JSON object in the model output")
    txt = txt[start:end + 1]
    try:
        return json.loads(txt)
    except json.JSONDecodeError:
        repaired = re.sub(r'"((?:[^"\\]|\\.)*)"', lambda m: '"' + m.group(1).replace("\n", "\\n").replace("\r", "") + '"', txt, flags=re.S)
        repaired = re.sub(r",\s*([}\]])", r"\1", repaired)          # trailing commas
        repaired = re.sub(r"//[^\n]*", "", repaired)                 # line comments
        return json.loads(repaired)


def _progress(step, status, progress, done=False, **extra):
    d = {"step": step, "status": status, "is_complete": done, "is_active": not done, "progress": progress}
    d.update(extra)
    return d


class IRFlow:
    def __init__(self, agent):
        self.agent = agent
        self.llm = getattr(agent, "expert_llm", None) or getattr(agent, "advanced_llm", None) or getattr(agent, "default_llm", None)
        self.model_name = (getattr(agent, "model_names", {}) or {}).get("expert") or "unknown"
        if self.llm is not None:
            self.extract_chain = ChatPromptTemplate.from_template(extract_ir_template) | self.llm | StrOutputParser()
            self.patch_chain = ChatPromptTemplate.from_template(patch_ir_template) | self.llm | StrOutputParser()
        else:
            self.extract_chain = self.patch_chain = None

    # ------------------------------------------------------------------ LLM

    async def _invoke(self, chain, inputs: dict, label: str, session_id: str) -> dict:
        if chain is None:
            raise RuntimeError("LLM not configured")
        tracker = self.agent._get_cost_tracker(session_id)
        last_exc = None
        for attempt in range(2):
            raw = await ainvoke_with_cost_tracking(label, chain.ainvoke, inputs, tracker, self.model_name)
            try:
                data = _parse_json(raw)
                log_template_io(IR_EXTRACT_LOG, session_id, label, inputs, raw)
                return data
            except ValueError as exc:
                last_exc = exc
                log_template_io(IR_EXTRACT_LOG, session_id, label, inputs, raw, error="bad JSON (attempt %d): %s" % (attempt + 1, exc))
        raise RuntimeError("the extractor returned no valid JSON: %s" % last_exc)

    async def extract(self, history_text: str, session_id: str) -> dict:
        return await self._invoke(self.extract_chain, {"history": history_text}, "ir_extract", session_id)

    async def patch(self, current_ir: dict, edit_text: str, selected_face: str, session_id: str) -> dict:
        return await self._invoke(self.patch_chain, {"current_ir": json.dumps(current_ir, ensure_ascii=False, indent=1),
                                                     "edit_text": edit_text, "selected_face": selected_face or "(none)"},
                                  "ir_patch", session_id)

    # ------------------------------------------------------------------ decide

    @staticmethod
    def prepare(envelope: dict) -> dict:
        """Turn the extractor envelope into a decision: questions / message / ready."""
        intent = str(envelope.get("intent") or "cad").lower()
        if intent == "assembly":
            return {"kind": "message", "message": ASSEMBLY_MESSAGE}
        if intent == "unsupported":
            reason = envelope.get("unsupported_reason") or "this shape is outside what I can model"
            return {"kind": "message", "message": "I cannot build this part: %s. %sPlease describe the part in those terms." % (reason, CAPABILITIES)}
        if intent in ("chat", "info"):
            return {"kind": "message", "message": envelope.get("reply") or CAPABILITIES}
        ir = part_to_dict(envelope.get("part"))
        if not ir:
            return {"kind": "message", "message": CAPABILITIES + "Please describe the part with its dimensions."}
        val = validate(ir)
        questions = list(envelope.get("questions") or [])
        llm_words = {w for q in questions for w in re.findall(r"[a-zà-ÿ]{5,}", q.lower())}
        for q in val.questions:
            # the extractor often asks the same thing in its own words ("which triangle definition...?"):
            # do not ask twice; the deterministic check runs again on the next turn anyway
            if q not in questions and not (llm_words & set(re.findall(r"[a-zà-ÿ]{5,}", q.lower()))):
                questions.append(q)
        for e in val.errors:
            questions.append("Please check: %s" % e)
        if questions:
            return {"kind": "questions", "message": format_questions(questions), "questions": questions, "ir": ir}
        return {"kind": "ready", "ir": ir, "validation": val,
                "assumptions": list(envelope.get("assumptions") or []),
                "skip_confirm": bool(envelope.get("skip_questions"))}

    # ------------------------------------------------------------------ turns

    async def turn(self, user_text: str, session_id: str, is_edit: bool, priority: int, start_time: float) -> AsyncIterator[dict]:
        state = self.agent._get_session_state(session_id)
        if is_edit and state.get("latest_ir"):
            async for upd in self._turn_edit(user_text, session_id, priority, start_time):
                yield upd
            return
        async for upd in self._turn_new(user_text, session_id, priority, start_time):
            yield upd

    async def _turn_new(self, user_text, session_id, priority, start_time) -> AsyncIterator[dict]:
        yield _progress("analysis", "Reading the request...", 15)
        # NOTE: an "ok" after a question is deliberately re-extracted with the full history:
        # the extractor may find the value it missed the first time (it did on the deck),
        # and the confirmation step still shows every value before anything is built.
        history = self.agent._build_user_text_with_history(session_id, user_text)
        envelope = await self.extract(history, session_id)
        prep = self.prepare(envelope)
        logger.info("[IR] extract -> %s | session=%s", prep["kind"], session_id)
        yield _progress("analysis", "Analysis completed.", 20, done=True, design_type="part")
        yield _progress("parameters", "Parameters validated.", 40, done=True)
        if prep["kind"] != "ready":
            self.agent._update_session_state(session_id, pending_questions=prep.get("questions") or [], ir_pending=None)
            yield {"final_result": {"code": None, "message": prep["message"], "explanation": None}}
            return
        ir, val = prep["ir"], prep["validation"]
        state = self.agent._get_session_state(session_id)
        confirm_count = state.get("confirm_count", 0)
        if not prep["skip_confirm"] and confirm_count < self.agent.MAX_CONFIRM_ATTEMPTS:
            desc = ir_render.description(val.ir, val.plan)
            msg = ir_render.confirm_message(val.ir, val.plan, warnings=val.warnings, assumptions=prep["assumptions"])
            self.agent._update_session_state(session_id, awaiting_confirm=True, confirm_count=confirm_count + 1,
                                             confirmed_description=desc, ir_pending=ir, pending_questions=[])
            yield {"final_result": {"code": None, "message": msg, "explanation": "Awaiting description confirmation (round %d/%d)" % (confirm_count + 1, self.agent.MAX_CONFIRM_ATTEMPTS)}}
            return
        async for upd in self._build(session_id, priority, ir, val, start_time, user_text):
            yield upd

    async def build_pending(self, session_id: str, priority: int, start_time: float, user_text: str = "") -> AsyncIterator[dict]:
        """The user said yes to the confirmation."""
        state = self.agent._get_session_state(session_id)
        ir = state.get("ir_pending")
        self.agent._update_session_state(session_id, awaiting_confirm=False, ir_pending=None)
        yield _progress("analysis", "Analysis completed (confirmed).", 20, done=True, design_type="part")
        yield _progress("parameters", "Parameters validated (from confirmed description).", 40, done=True)
        val = validate(ir)
        if not val.ok:
            yield {"final_result": {"code": None, "message": format_questions(val.questions + val.errors), "explanation": None}}
            return
        async for upd in self._build(session_id, priority, ir, val, start_time, user_text):
            yield upd

    async def _turn_edit(self, user_text, session_id, priority, start_time) -> AsyncIterator[dict]:
        state = self.agent._get_session_state(session_id)
        current = state["latest_ir"]
        yield _progress("analysis", "Analysis completed - edit mode.", 20, done=True)
        yield _progress("parameters", "Applying the change to the part description...", 40)
        face_hint, edit_text = "", user_text
        try:
            face_data = self.agent.face_processor.parse_face_selection(user_text)
        except Exception:
            face_data = None
        if face_data:
            edit_text = user_text.replace(face_data.get("original_text", ""), "").strip()
            face_hint = self._nearest_face(current, face_data) or ""
        try:
            edit_history = self.agent._build_post_codegen_history(session_id, edit_text)
        except Exception:
            edit_history = "[USER]: %s\n" % edit_text
        envelope = await self.patch(current, edit_history, face_hint, session_id)
        prep = self.prepare(envelope)
        if prep["kind"] != "ready":
            self.agent._update_session_state(session_id, pending_questions=prep.get("questions") or [])
            yield {"final_result": {"code": None, "message": prep["message"], "explanation": None}}
            return
        ir, val = prep["ir"], prep["validation"]
        if val.warnings:
            # surface DFM warnings but do not block an edit (the user asked for it)
            logger.info("[IR][EDIT] warnings: %s", val.warnings)
        async for upd in self._build(session_id, priority, ir, val, start_time, user_text, edit_summary=envelope.get("summary")):
            yield upd

    def _nearest_face(self, current_ir: dict, face_data: dict) -> Optional[str]:
        try:
            nir, plan = F.plan_part(current_ir)
        except Exception:
            return None
        c = face_data["bbox"]["min"], face_data["bbox"]["max"]
        cx, cy, cz = ((c[0][k] + c[1][k]) / 2.0 for k in ("x", "y", "z"))
        best, best_d = None, 1e18
        for name in plan.order:
            f = plan.faces[name]
            p = f.point(f.U / 2.0, f.V / 2.0, nir.get("thickness", 0) / 2.0)
            d = (p[0] - cx) ** 2 + (p[1] - cy) ** 2 + (p[2] - cz) ** 2
            if d < best_d:
                best, best_d = name, d
        return best

    # ------------------------------------------------------------------ build

    async def _build(self, session_id, priority, ir, val, start_time, user_text, edit_summary=None) -> AsyncIterator[dict]:
        nir, plan = val.ir, val.plan
        desc = ir_render.description(nir, plan)
        title = sanitize_title(nir.get("name") or plan.label)
        code = make_stub_script(nir, title, nir.get("material"))
        requirements = AnalysisAndParameterCheckOutput(complexity_level=2, missing_info=False, shape_type=plan.label,
                                                       title=title, description=desc)
        yield _progress("generation_code", "Part description ready, no code generation needed.", 70, done=True)
        export_start = time.time()
        eta = self.agent._build_export_eta_payload(session_id, export_start)
        yield _progress("export", "Building the part in FreeCAD...", 80, **eta)
        result = {"code": code, "message": None, "explanation": desc, "ir": nir, "shape_type": plan.label}
        if edit_summary:
            result["edit_summary"] = edit_summary
        try:
            task = asyncio.create_task(self.agent.save_outputs(code, requirements, user_text=user_text, session_id=session_id,
                                                               priority=priority, skip_metadata=True))
            while True:
                try:
                    obj_path, step_path, pdf_path = await asyncio.wait_for(asyncio.shield(task), timeout=15)
                    break
                except asyncio.TimeoutError:
                    yield _progress("export", "Building the part in FreeCAD...", 80, **self.agent._build_export_eta_payload(session_id, export_start))
            result.update({"obj_path": obj_path, "step_path": step_path, "pdf_path": pdf_path})
        except Exception as exc:
            logger.error("[IR] export failed | code=%s | %s | session=%s", error_code_of(exc), exc, session_id)
            result["error"] = as_user_error(exc)
            result["code"] = None
        else:
            self.agent._update_session_state(session_id, latest_ir=nir, latest_code=code, latest_title=title,
                                             latest_requirements=requirements, awaiting_confirm=False, confirm_count=0,
                                             confirmed_description="", ir_pending=None, pending_questions=[],
                                             edit_running_summary=desc)
        yield _progress("export", "Export completed.", 95, done=True, **self.agent._build_export_eta_payload(session_id, export_start))
        yield _progress("complete", "All processing completed!", 100, done=True)
        logger.info("[IR] turn done in %.1fs | session=%s", time.time() - start_time, session_id)
        yield {"final_result": result}
